name: flutter_local_notifications_app
description: 'Flutter example project with local notifications.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter_launcher_icons:
  adaptive_icon_background: 'assets/images/ic_launcher_background.png'
  adaptive_icon_foreground: 'assets/images/ic_launcher_foreground.png'
  adaptive_icon_foreground_inset: 0
  adaptive_icon_monochrome: 'assets/images/ic_launcher_monochrome.png'
  android: true
  image_path: 'assets/images/ic_launcher.png'
  ios: false
  macos:
    generate: false
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false

flutter:
  uses-material-design: true
