name: flutter_local_notifications_app
description: 'Flutter example project with local notifications.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  easy_notifications: ^1.1.9
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter_launcher_icons:
  adaptive_icon_background: 'assets/icons/android/ic_launcher_background.png'
  adaptive_icon_foreground: 'assets/icons/android/ic_launcher_foreground.png'
  adaptive_icon_foreground_inset: 0
  adaptive_icon_monochrome: 'assets/icons/android/ic_launcher_monochrome.png'
  android: true
  image_path_android: 'assets/icons/android/ic_launcher.png'
  image_path_ios: 'assets/icons/ios/app-icon.png'
  ios: true
  macos:
    generate: false
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: false

flutter:
  uses-material-design: true
